//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.20 at 10:49:14 PM CST 
//


package com.cognizant.unik.service.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Condition">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QuestionCondition" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="questID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="conditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Decision">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DecisionCondition" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="decisionkey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="decisionValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Rule")
public class Rule {

    @XmlElementRefs({
        @XmlElementRef(name = "Condition", type = JAXBElement.class),
        @XmlElementRef(name = "Decision", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Condition }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Decision }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QuestionCondition" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="questID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="conditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "questionCondition"
    })
    public static class Condition {

        @XmlElement(name = "QuestionCondition")
        protected List<QuestionCondition> questionCondition;

        /**
         * Gets the value of the questionCondition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the questionCondition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestionCondition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QuestionCondition }
         * 
         * 
         */
        public List<QuestionCondition> getQuestionCondition() {
            if (questionCondition == null) {
                questionCondition = new ArrayList<QuestionCondition>();
            }
            return this.questionCondition;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="questID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="conditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "questID",
            "conditional",
            "answerValue"
        })
        public static class QuestionCondition {

            @XmlElement(required = true)
            protected String questID;
            @XmlElement(required = true)
            protected String conditional;
            @XmlElement(required = true)
            protected String answerValue;

            /**
             * Gets the value of the questID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuestID() {
                return questID;
            }

            /**
             * Sets the value of the questID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuestID(String value) {
                this.questID = value;
            }

            /**
             * Gets the value of the conditional property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConditional() {
                return conditional;
            }

            /**
             * Sets the value of the conditional property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConditional(String value) {
                this.conditional = value;
            }

            /**
             * Gets the value of the answerValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnswerValue() {
                return answerValue;
            }

            /**
             * Sets the value of the answerValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnswerValue(String value) {
                this.answerValue = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DecisionCondition" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="decisionkey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="decisionValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "decisionCondition"
    })
    public static class Decision {

        @XmlElement(name = "DecisionCondition")
        protected List<DecisionCondition> decisionCondition;

        /**
         * Gets the value of the decisionCondition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the decisionCondition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDecisionCondition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DecisionCondition }
         * 
         * 
         */
        public List<DecisionCondition> getDecisionCondition() {
            if (decisionCondition == null) {
                decisionCondition = new ArrayList<DecisionCondition>();
            }
            return this.decisionCondition;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="decisionkey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="decisionValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "decisionkey",
            "decisionValue"
        })
        public static class DecisionCondition {

            @XmlElement(required = true)
            protected String decisionkey;
            @XmlElement(required = true)
            protected String decisionValue;

            /**
             * Gets the value of the decisionkey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDecisionkey() {
                return decisionkey;
            }

            /**
             * Sets the value of the decisionkey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDecisionkey(String value) {
                this.decisionkey = value;
            }

            /**
             * Gets the value of the decisionValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDecisionValue() {
                return decisionValue;
            }

            /**
             * Sets the value of the decisionValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDecisionValue(String value) {
                this.decisionValue = value;
            }

        }

    }

}
